  version: "3"
  services:
    api-database:
      image: mongo:4.2.0
      container_name: "api-database"
      ports:
        - 27017:27017
      command: --smallfiles
    api:
      image: api-docker-image
      ports:
        - 8080:8080
      links:
        - api-database
      command: mvn clean spring-boot:run